### ISSUE TITLE
Security-Concept für Frontend überlegen

### ISSUE THREAD

**Issue by busch-matthias** [Chatbot-Challenge/Frontend#14]
wolllen wir API-Calls zulassen 
+ externe bibs wollen wir wissen `requirements.txt'

**Comment by ingosiegert** [comment]
Normaler nutzer  der Gruppe user. Dann kommt es drauf an, wie das Front-End arbeitet? Ist das ein Webservice, dann braucht man als nutzer Zugriff auf den entsprechenden Ordner (wird meist darüber gelöst, dass man dann auch Mitglied der Gruppe des Webservers ist)

**Comment by jnehring** [comment]
wird mit #23 erledigt
