### ISSUE TITLE
Readme mit GDoc abgleichen

### ISSUE THREAD

**Issue by jnehring** [Chatbot-Challenge/Frontend#24]
Die Infos von GDoc in die Readme einbauen: https://docs.google.com/document/d/1tzUeq8GJczFe6lUSCROhjWtEXmT9cZXuUmZ35t9Z-1U/edit#

**Comment by busch-matthias** [comment]
is in #27

**Comment by jnehring** [comment]
Ich habe die Deployment Instructions in GDoc geupdated. Da fehlten dann doch noch einige Infos in der Readme. Wir schicken den Studis diesen Link mit der Anleitung für das Deployment.

Bitte beachten: Alle Gruppen sollen das bis Montag (5. Juni) abend gemacht haben, damit ich am Montag früh deployen kann. Der Bot muss nicht "fertig" sein, aber wir wollen eine erste Version haben um das Deployment zu testen. 

https://docs.google.com/document/d/1tzUeq8GJczFe6lUSCROhjWtEXmT9cZXuUmZ35t9Z-1U/edit?usp=sharing
