### ISSUE TITLE
Rasa config.yml

### ISSUE THREAD

**Issue by jnehring** [Chatbot-Challenge/Frontend#5]
How do we configure rasas config.yml? Which processing pipeline do we use?

This is the Rasa default pipeline. Anything wrong with that?: https://github.com/Chatbot-Challenge/Frontend/blob/main/escape-rooms/rasa-default-bot/config.yml

**Comment by busch-matthias** [comment]
FYI  ich habe in dem "Rasa Template" repo einen entsprechenend Issue erstellt :
chatbot-challenge/Rasa-Template#1
